### ISSUE TITLE
How to use the trained models?

### ISSUE THREAD

**Issue by hyang23333** [ManojPrabhakar/Ball-Tracking-and-Detection#1]
Thanks for the great work! 
Now I have my soccer video and is it possible to track the location of the soccer ball in every frame via your trained models? And how can I do this? Cause I am very unfamiliar with this, any help would be appreciated!
Thanks again!

**Comment by ManojPrabhakar** [comment]
@hyang23333 Thank you!!

You should convert the video frames into images of dimensions specified in the report and then update the test_files in the evaluation part of the code. Then, you can load these models and run them.

These models were trained on a small custom dataset, which is specific to my purpose. The tracking accuracy might be less for your data. Please consider training the model from scratch.
